# Generated by Django 3.1.4 on 2021-01-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_medicine_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test')),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(upload_to='medicines'),
        ),
    ]
